# Generated by Django 2.0 on 2020-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_drags', models.CharField(max_length=300)),
                ('class_of_danger', models.CharField(max_length=1)),
                ('way_of_recycling', models.CharField(max_length=600)),
            ],
        ),
    ]
