# Generated by Django 2.0 on 2020-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=50)),
                ('ecol_risk', models.CharField(max_length=50)),
                ('index_PBT', models.IntegerField(default=0)),
                ('index_P', models.IntegerField(default=0)),
                ('index_B', models.IntegerField(default=0)),
                ('index_T', models.IntegerField(default=0)),
                ('inactive_metabolite', models.CharField(max_length=500)),
                ('inactivation_reagent', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Drags',
        ),
    ]
