# Generated by Django 2.0 on 2020-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201006_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_tab',
            name='index_B',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='first_tab',
            name='index_P',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='first_tab',
            name='index_PBT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='first_tab',
            name='index_T',
            field=models.IntegerField(null=True),
        ),
    ]
