# Generated by Django 2.0 on 2020-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201006_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=50)),
                ('lc50_c', models.FloatField(null=True)),
                ('lc50_d', models.FloatField(null=True)),
                ('coef_bioaccum', models.FloatField(null=True)),
                ('ld50', models.FloatField(null=True)),
            ],
        ),
    ]
