# Generated by Django 2.0 on 2020-10-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_second_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_tab',
            name='index_B',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_tab',
            name='index_P',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_tab',
            name='index_PBT',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_tab',
            name='index_T',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
