# Generated by Django 2.0 on 2020-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201024_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_tad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_ath', models.CharField(max_length=1000)),
                ('drug', models.CharField(max_length=50)),
                ('commercial_name', models.CharField(max_length=1000)),
                ('ecol_risk', models.CharField(max_length=50)),
                ('index_PBT', models.CharField(max_length=5, null=True)),
                ('index_P', models.CharField(max_length=5, null=True)),
                ('index_B', models.CharField(max_length=5, null=True)),
                ('index_T', models.CharField(max_length=5, null=True)),
                ('inactive_metabolite', models.CharField(max_length=500)),
                ('inactivation_reagent', models.CharField(max_length=500)),
                ('lc50_c_original', models.FloatField(null=True)),
                ('lc50_c_product', models.FloatField(null=True)),
                ('lc50_d_original', models.FloatField(null=True)),
                ('lc50_d_product', models.FloatField(null=True)),
                ('coef_bioaccum_original', models.FloatField(null=True)),
                ('coef_bioaccum_product', models.FloatField(null=True)),
                ('ld50_original', models.FloatField(null=True)),
                ('ld50_product', models.FloatField(null=True)),
            ],
        ),
    ]
